"""phase2_initial_schema

Revision ID: 07be455430c8
Revises: 
Create Date: 2026-05-07 09:38:30.034122
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.crypto  # noqa: F401  -- needed for EncryptedText column type


revision: str = '07be455430c8'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label_ko', sa.String(length=120), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_key', sa.String(length=60), nullable=False),
    sa.Column('title_enc', app.core.crypto.EncryptedText(), nullable=True),
    sa.Column('body_enc', app.core.crypto.EncryptedText(), nullable=True),
    sa.Column('reporter_enc', app.core.crypto.EncryptedText(), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=True),
    sa.Column('assignee', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DONE', 'REJECTED', name='ticketstatus'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.create_index(op.f('ix_tickets_jira_key'), 'tickets', ['jira_key'], unique=True)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', name='userrole'), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('webhook_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_key', sa.String(length=60), nullable=False),
    sa.Column('changelog_id', sa.String(length=80), nullable=False),
    sa.Column('payload_enc', app.core.crypto.EncryptedText(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', name='inboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_inbox')),
    sa.UniqueConstraint('jira_key', 'changelog_id', name='uq_webhook_inbox_jira_changelog')
    )
    op.create_index(op.f('ix_webhook_inbox_jira_key'), 'webhook_inbox', ['jira_key'], unique=False)
    op.create_table('kpi_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('WEBHOOK_RECEIVED', 'DRAFT_GENERATED', 'DRAFT_VIEWED', 'DRAFT_EDITED', 'DRAFT_APPROVED', 'DRAFT_REJECTED', 'CLASSIFICATION_CORRECTED', 'RESPONSE_SENT', name='kpieventtype'), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_kpi_events_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_events'))
    )
    op.create_index(op.f('ix_kpi_events_event_type'), 'kpi_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_kpi_events_ticket_id'), 'kpi_events', ['ticket_id'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('VIEW', 'EDIT', 'APPROVE', 'REJECT', 'RECLASSIFY', 'REGENERATE', name='actiontype'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_operator_actions_ticket_id_tickets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operator_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_actions'))
    )
    op.create_index(op.f('ix_operator_actions_ticket_id'), 'operator_actions', ['ticket_id'], unique=False)
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_uploads_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index(op.f('ix_uploads_sha256'), 'uploads', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_sha256'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_index(op.f('ix_operator_actions_ticket_id'), table_name='operator_actions')
    op.drop_table('operator_actions')
    op.drop_index(op.f('ix_kpi_events_ticket_id'), table_name='kpi_events')
    op.drop_index(op.f('ix_kpi_events_event_type'), table_name='kpi_events')
    op.drop_table('kpi_events')
    op.drop_index(op.f('ix_webhook_inbox_jira_key'), table_name='webhook_inbox')
    op.drop_table('webhook_inbox')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_jira_key'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('categories')
    # ### end Alembic commands ###
