"""phase4_llm_drafts_classifications

Revision ID: 8df2a6bbdd67
Revises: 07be455430c8
Create Date: 2026-05-11 14:52:13.205564
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8df2a6bbdd67'
down_revision: str | Sequence[str] | None = '07be455430c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('predicted_category_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('was_corrected', sa.Boolean(), nullable=False),
    sa.Column('corrected_by', sa.Integer(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_classifications_category_id_categories')),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], name=op.f('fk_classifications_corrected_by_users')),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], name=op.f('fk_classifications_predicted_category_id_categories')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_classifications_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classifications'))
    )
    op.create_index(op.f('ix_classifications_ticket_id'), 'classifications', ['ticket_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CLASSIFY', 'DRAFT', name='promptkind'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_prompt_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates'))
    )
    op.create_index(op.f('ix_prompt_templates_is_active'), 'prompt_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_prompt_templates_kind'), 'prompt_templates', ['kind'], unique=False)
    op.create_table('references_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_references__ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_references_'))
    )
    op.create_index(op.f('ix_references__ticket_id'), 'references_', ['ticket_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_html_edited', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('edit_distance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], name=op.f('fk_drafts_prompt_template_id_prompt_templates')),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_drafts_ticket_id_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts'))
    )
    op.create_index(op.f('ix_drafts_ticket_id'), 'drafts', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drafts_ticket_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_references__ticket_id'), table_name='references_')
    op.drop_table('references_')
    op.drop_index(op.f('ix_prompt_templates_kind'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_is_active'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_classifications_ticket_id'), table_name='classifications')
    op.drop_table('classifications')
    # ### end Alembic commands ###
